"""removed invitations table

Revision ID: 2a42e4ba28de
Revises: e73ea90abaa0
Create Date: 2025-06-29 17:14:59.002509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a42e4ba28de'
down_revision = 'e73ea90abaa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_invitations_event_id_events'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_invitations_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_invitations')
    )
    # ### end Alembic commands ###
