"""Changed event.date from DateTime to Text

Revision ID: 5cb6fb4865a4
Revises: a80f22a70cdf
Create Date: 2025-06-26 01:52:37.642639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb6fb4865a4'
down_revision = 'a80f22a70cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
